// Generated by tools/build_gallery.py. Do not edit manually.
window.RASSVET_GALLERY = [
  {
    "id": "01-01-hero",
    "category": "Under sail",
    "caption": "Hero",
    "alt": "Rassvet — Hero",
    "thumbnail": {
      "webp": "photos/generated/01-01-hero-thumb.webp",
      "jpeg": "photos/generated/01-01-hero-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-01-hero-full.webp",
      "jpeg": "photos/generated/01-01-hero-full.jpg"
    },
    "width": 2160,
    "height": 3840,
    "portrait": true,
    "lead": true
  },
  {
    "id": "01-02-img-7258",
    "category": "Under sail",
    "caption": "Under sail 2",
    "alt": "Rassvet — Under sail 2",
    "thumbnail": {
      "webp": "photos/generated/01-02-img-7258-thumb.webp",
      "jpeg": "photos/generated/01-02-img-7258-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-02-img-7258-full.webp",
      "jpeg": "photos/generated/01-02-img-7258-full.jpg"
    },
    "width": 960,
    "height": 1280,
    "portrait": true,
    "lead": false
  },
  {
    "id": "01-03-unknown",
    "category": "Under sail",
    "caption": "Unknown",
    "alt": "Rassvet — Unknown",
    "thumbnail": {
      "webp": "photos/generated/01-03-unknown-thumb.webp",
      "jpeg": "photos/generated/01-03-unknown-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-03-unknown-full.webp",
      "jpeg": "photos/generated/01-03-unknown-full.jpg"
    },
    "width": 4608,
    "height": 3456,
    "portrait": false,
    "lead": false
  },
  {
    "id": "01-04-unknown",
    "category": "Under sail",
    "caption": "Unknown",
    "alt": "Rassvet — Unknown",
    "thumbnail": {
      "webp": "photos/generated/01-04-unknown-thumb.webp",
      "jpeg": "photos/generated/01-04-unknown-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-04-unknown-full.webp",
      "jpeg": "photos/generated/01-04-unknown-full.jpg"
    },
    "width": 3456,
    "height": 4608,
    "portrait": true,
    "lead": false
  },
  {
    "id": "01-05-img-7492",
    "category": "Under sail",
    "caption": "Under sail 5",
    "alt": "Rassvet — Under sail 5",
    "thumbnail": {
      "webp": "photos/generated/01-05-img-7492-thumb.webp",
      "jpeg": "photos/generated/01-05-img-7492-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-05-img-7492-full.webp",
      "jpeg": "photos/generated/01-05-img-7492-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "01-06-img-9997",
    "category": "Under sail",
    "caption": "Under sail 6",
    "alt": "Rassvet — Under sail 6",
    "thumbnail": {
      "webp": "photos/generated/01-06-img-9997-thumb.webp",
      "jpeg": "photos/generated/01-06-img-9997-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/01-06-img-9997-full.webp",
      "jpeg": "photos/generated/01-06-img-9997-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "02-01-dji-fly-20250815-200704-0018-1755281265707-photo",
    "category": "Exterior",
    "caption": "Dji fly 20250815 200704 0018 1755281265707 photo",
    "alt": "Rassvet — Dji fly 20250815 200704 0018 1755281265707 photo",
    "thumbnail": {
      "webp": "photos/generated/02-01-dji-fly-20250815-200704-0018-1755281265707-photo-thumb.webp",
      "jpeg": "photos/generated/02-01-dji-fly-20250815-200704-0018-1755281265707-photo-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/02-01-dji-fly-20250815-200704-0018-1755281265707-photo-full.webp",
      "jpeg": "photos/generated/02-01-dji-fly-20250815-200704-0018-1755281265707-photo-full.jpg"
    },
    "width": 3804,
    "height": 2852,
    "portrait": false,
    "lead": false
  },
  {
    "id": "02-02-img-4249",
    "category": "Exterior",
    "caption": "Exterior 2",
    "alt": "Rassvet — Exterior 2",
    "thumbnail": {
      "webp": "photos/generated/02-02-img-4249-thumb.webp",
      "jpeg": "photos/generated/02-02-img-4249-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/02-02-img-4249-full.webp",
      "jpeg": "photos/generated/02-02-img-4249-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "02-03-img-20250802-103658-674",
    "category": "Exterior",
    "caption": "IMG 20250802 103658 674",
    "alt": "Rassvet — IMG 20250802 103658 674",
    "thumbnail": {
      "webp": "photos/generated/02-03-img-20250802-103658-674-thumb.webp",
      "jpeg": "photos/generated/02-03-img-20250802-103658-674-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/02-03-img-20250802-103658-674-full.webp",
      "jpeg": "photos/generated/02-03-img-20250802-103658-674-full.jpg"
    },
    "width": 2160,
    "height": 3840,
    "portrait": true,
    "lead": false
  },
  {
    "id": "02-04-img-20250802-104018-448",
    "category": "Exterior",
    "caption": "IMG 20250802 104018 448",
    "alt": "Rassvet — IMG 20250802 104018 448",
    "thumbnail": {
      "webp": "photos/generated/02-04-img-20250802-104018-448-thumb.webp",
      "jpeg": "photos/generated/02-04-img-20250802-104018-448-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/02-04-img-20250802-104018-448-full.webp",
      "jpeg": "photos/generated/02-04-img-20250802-104018-448-full.jpg"
    },
    "width": 2160,
    "height": 3840,
    "portrait": true,
    "lead": false
  },
  {
    "id": "03-01-img-1948",
    "category": "Deck and cockpit",
    "caption": "Deck and cockpit 1",
    "alt": "Rassvet — Deck and cockpit 1",
    "thumbnail": {
      "webp": "photos/generated/03-01-img-1948-thumb.webp",
      "jpeg": "photos/generated/03-01-img-1948-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/03-01-img-1948-full.webp",
      "jpeg": "photos/generated/03-01-img-1948-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "03-02-img-6710",
    "category": "Deck and cockpit",
    "caption": "Deck and cockpit 2",
    "alt": "Rassvet — Deck and cockpit 2",
    "thumbnail": {
      "webp": "photos/generated/03-02-img-6710-thumb.webp",
      "jpeg": "photos/generated/03-02-img-6710-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/03-02-img-6710-full.webp",
      "jpeg": "photos/generated/03-02-img-6710-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "03-03-img-7369",
    "category": "Deck and cockpit",
    "caption": "Deck and cockpit 3",
    "alt": "Rassvet — Deck and cockpit 3",
    "thumbnail": {
      "webp": "photos/generated/03-03-img-7369-thumb.webp",
      "jpeg": "photos/generated/03-03-img-7369-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/03-03-img-7369-full.webp",
      "jpeg": "photos/generated/03-03-img-7369-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "05-01-img-6842",
    "category": "Engine and systems",
    "caption": "Engine and systems 1",
    "alt": "Rassvet — Engine and systems 1",
    "thumbnail": {
      "webp": "photos/generated/05-01-img-6842-thumb.webp",
      "jpeg": "photos/generated/05-01-img-6842-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/05-01-img-6842-full.webp",
      "jpeg": "photos/generated/05-01-img-6842-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "05-02-img-7923",
    "category": "Engine and systems",
    "caption": "Engine and systems 2",
    "alt": "Rassvet — Engine and systems 2",
    "thumbnail": {
      "webp": "photos/generated/05-02-img-7923-thumb.webp",
      "jpeg": "photos/generated/05-02-img-7923-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/05-02-img-7923-full.webp",
      "jpeg": "photos/generated/05-02-img-7923-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "05-03-img-7850",
    "category": "Engine and systems",
    "caption": "Engine and systems 3",
    "alt": "Rassvet — Engine and systems 3",
    "thumbnail": {
      "webp": "photos/generated/05-03-img-7850-thumb.webp",
      "jpeg": "photos/generated/05-03-img-7850-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/05-03-img-7850-full.webp",
      "jpeg": "photos/generated/05-03-img-7850-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-01-img-6660",
    "category": "Underwater hull",
    "caption": "Underwater hull 1",
    "alt": "Rassvet — Underwater hull 1",
    "thumbnail": {
      "webp": "photos/generated/07-01-img-6660-thumb.webp",
      "jpeg": "photos/generated/07-01-img-6660-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-01-img-6660-full.webp",
      "jpeg": "photos/generated/07-01-img-6660-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-02-img-6792",
    "category": "Underwater hull",
    "caption": "Underwater hull 2",
    "alt": "Rassvet — Underwater hull 2",
    "thumbnail": {
      "webp": "photos/generated/07-02-img-6792-thumb.webp",
      "jpeg": "photos/generated/07-02-img-6792-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-02-img-6792-full.webp",
      "jpeg": "photos/generated/07-02-img-6792-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-03-img-6794",
    "category": "Underwater hull",
    "caption": "Underwater hull 3",
    "alt": "Rassvet — Underwater hull 3",
    "thumbnail": {
      "webp": "photos/generated/07-03-img-6794-thumb.webp",
      "jpeg": "photos/generated/07-03-img-6794-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-03-img-6794-full.webp",
      "jpeg": "photos/generated/07-03-img-6794-full.jpg"
    },
    "width": 4032,
    "height": 3024,
    "portrait": false,
    "lead": false
  },
  {
    "id": "07-04-img-6795",
    "category": "Underwater hull",
    "caption": "Underwater hull 4",
    "alt": "Rassvet — Underwater hull 4",
    "thumbnail": {
      "webp": "photos/generated/07-04-img-6795-thumb.webp",
      "jpeg": "photos/generated/07-04-img-6795-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-04-img-6795-full.webp",
      "jpeg": "photos/generated/07-04-img-6795-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-05-img-6796",
    "category": "Underwater hull",
    "caption": "Underwater hull 5",
    "alt": "Rassvet — Underwater hull 5",
    "thumbnail": {
      "webp": "photos/generated/07-05-img-6796-thumb.webp",
      "jpeg": "photos/generated/07-05-img-6796-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-05-img-6796-full.webp",
      "jpeg": "photos/generated/07-05-img-6796-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-06-img-6797",
    "category": "Underwater hull",
    "caption": "Underwater hull 6",
    "alt": "Rassvet — Underwater hull 6",
    "thumbnail": {
      "webp": "photos/generated/07-06-img-6797-thumb.webp",
      "jpeg": "photos/generated/07-06-img-6797-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-06-img-6797-full.webp",
      "jpeg": "photos/generated/07-06-img-6797-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  },
  {
    "id": "07-07-img-6807",
    "category": "Underwater hull",
    "caption": "Underwater hull 7",
    "alt": "Rassvet — Underwater hull 7",
    "thumbnail": {
      "webp": "photos/generated/07-07-img-6807-thumb.webp",
      "jpeg": "photos/generated/07-07-img-6807-thumb.jpg"
    },
    "full": {
      "webp": "photos/generated/07-07-img-6807-full.webp",
      "jpeg": "photos/generated/07-07-img-6807-full.jpg"
    },
    "width": 3024,
    "height": 4032,
    "portrait": true,
    "lead": false
  }
];
